tap "homebrew/cask-fonts"
tap "blackfireio/homebrew-blackfire"
tap "homebrew/cask-versions"
tap "shivammathur/extensions"

brew "wget"
brew "antigen"
brew "php@8.0"
brew "php"
brew "composer"
brew "gibo"
brew "mas"
brew "nss"
brew "pipenv"
brew "gh"
brew "yarn"
brew "blackfire"
brew "blackfire-php80"
brew "blackfire-php81"
brew "shivammathur/extensions/xdebug@8.0"
brew "shivammathur/extensions/xdebug@8.1"
brew "shivammathur/extensions/apcu@8.0"
brew "shivammathur/extensions/apcu@8.1"
brew "shivammathur/extensions/redis@8.0"
brew "shivammathur/extensions/redis@8.1"
brew "bat"
brew "bat-extras"
brew "ripgrep"
brew "git-delta"
brew "watchman"

cask "hyper"
cask "visual-studio-code"
cask "gpg-suite-no-mail"
cask "font-hack"
cask "github"
cask "docker"
cask "signal"
cask "discord"
cask "skype"
cask "jetbrains-toolbox"
cask "libreoffice"
cask "balenaetcher"
cask "ngrok"
cask "box-notes"
cask "altair-graphql-client"
cask "lastpass"
cask "firefox-developer-edition"
cask "slack"
cask "pastebot"
cask "dash"
cask "calibre"

mas "Moom", id: 419330170
mas "Todoist", id: 585829637
mas "BBedit", id: 404009241
mas "Unclutter", id: 577085396
mas "Amphetamine", id: 937984704
mas "Rename It", id: 443773246
mas "AutoMute - No More Oopsies", id: 1118136179
mas "Keynote", id: 409183694
