#!/usr/bin/env zsh

# Do this in a script because nvm isn't a binarry it is a function so it has to be sourced
# before it can be used.

source ~/.antigen/bundles/lukechilds/zsh-nvm/zsh-nvm.plugin.zsh

nvm install "lts/gallium" # 16.x
npm install -g npm
npm list -g ember-cli || npm install -g ember-cli
npm list -g nodemon || npm install -g nodemon

nvm install "lts/fermium" # 14.x
npm list -g ember-cli || npm install -g ember-cli
npm list -g nodemon || npm install -g nodemon
nvm alias default "lts/fermium"
nvm use default
